language: python
addons:
  postgresql: "9.4"

python:
  - "2.7"
install:
  - createdb -U postgres tag
  - pip install flake8
  - pip install -r requirements.txt
  - touch amsel/local_settings.py
script:
  - python manage.py syncdb --noinput
  - flake8 --exclude migrations --ignore E501,C901 ./
  - python manage.py test --noinput
notifications:
  slack:
    rooms:
      - ehealthafrica:vuLN0Q0ZvYCaYbxCdR0NwKxq#tag-travis
