db:
    image: "postgres:9.4"
    net: "host"
web:
  build: .
  volumes:
   - .:/opt/tag/
  net: "host"
rabbitmq:
    image: "docker"
    net: "host"
    ports:
     - "5672:5672"
     - "15672:15672"
