patient_info = "The patient %(first_name)s %(second_name)s has the information code %(unfo_code)s"
patient_location = "The patient %(first_name)s %(second_name)s is at %(h_facility)s"
patient_status = "The patient %(first_name)s %(second_name)s is currently %(status)s"
patient_no_info = "The system has not updated the location of the patient."
patient_not_found = 'We can not find a patient with that information id.'
invalid_id = 'This is not a valid information id.'
too_many_requests = "Please only send one message at a time. This query was ignored"
too_many_requests_ever = "You have sent too many requests from this number and have been blocked."
initial_message = "You will be notified of all changes in the status and location of your loved one."
